apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: linkerd
    git:
      url: https://github.com/giantswarm/linkerd2-upstream
      ref: stable-2.13.x
    includePaths:
    - charts/linkerd-control-plane/**/*
    - charts/linkerd-crds/**/*
    - charts/partials/**/*
- path: helm/linkerd-control-plane/templates
  contents:
  - path: .
    directory:
      path: vendor/linkerd/charts/linkerd-control-plane/templates
- path: helm/linkerd-control-plane/charts/partials
  contents:
  - path: .
    directory:
      path: vendor/linkerd/charts/partials
- path: helm/linkerd-control-plane/charts/linkerd-crds
  contents:
  - path: .
    directory:
      path: vendor/linkerd/charts/linkerd-crds
