apiVersion: v1
appVersion: stable-2.7.1
description: Linkerd gives you observability, reliability, and security for your microservices
  — with no code change required.
home: https://linkerd.io
icon: https://linkerd.io/images/logo-only-200h.png
keywords:
- service-mesh
kubeVersion: '>=1.13.0-0'
maintainers:
- email: cncf-linkerd-dev@lists.cncf.io
  name: Linkerd authors
  url: https://linkerd.io/
- name: Giant Swarm applications team
  url: https://github.com/giantswarm/linkerd2-app
name: linkerd2-app
sources:
- https://github.com/linkerd/linkerd2/
- https://github.com/giantswarm/linkerd2-app
version: [[ .Version ]]
  #version: 2.7.1
