apiVersion: v1
appVersion: edge-19.11.2
description: Linkerd gives you observability, reliability, and security for your microservices
  — with no code change required.
home: https://linkerd.io
icon: https://linkerd.io/images/logo-only-200h.png
keywords:
- service-mesh
kubeVersion: '>=1.12.0-0'
maintainers:
- email: cncf-linkerd-dev@lists.cncf.io
  name: Linkerd authors
  url: https://linkerd.io/
name: linkerd2
sources:
- https://github.com/linkerd/linkerd2/
version: 19.11.2
