# Default values for linkerd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Values that are passed along to sub-charts
global:
  clusterDomain: &cluster_domain cluster.local
  imagePullPolicy: &image_pull_policy IfNotPresent
  
  # Control Plane Trace Configuration
  controlPlaneTracing: false

  # control plane version. See Proxy section for proxy version
  linkerdVersion: &linkerd_version stable-2.7.1

  namespace: linkerd

  identityTrustAnchorsPEM: |

  identityTrustDomain: *cluster_domain

  # proxy configuration
  proxy:
    enableExternalProfiles: false
    image:
      name: gcr.io/linkerd-io/proxy
      pullPolicy: *image_pull_policy
      version: *linkerd_version
    logLevel: warn,linkerd=info
    ports:
      admin: 4191
      control: 4190
      inbound: 4143
      outbound: 4140
    resources:
      cpu:
        limit: ""
        request: ""
      memory:
        limit: ""
        request: ""
    trace:
      collectorSvcAddr: ""
      collectorSvcAccount: default
    uid: 2102
    # If set, the proxy's pre-stop hook will postpone the Kubernetes's SIGTERM signal
    # and wait for this duration before letting the proxy process the SIGTERM signal.
    # See https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks
    # for more info on container lifecycle hooks.
    waitBeforeExitSeconds: 0

  # proxy-init configuration
  proxyInit:
    ignoreInboundPorts: ""
    ignoreOutboundPorts: ""
    image:
      name: gcr.io/linkerd-io/proxy-init
      pullPolicy: *image_pull_policy
      version: v1.3.2
    resources:
      cpu:
        limit: 100m
        request: 10m
      memory:
        limit: 50Mi
        request: 10Mi

  # control plane annotations - do not edit
  createdByAnnotation: linkerd.io/created-by
  proxyInjectAnnotation: linkerd.io/inject
  proxyInjectDisabled: disabled

  # control plane labels - do not edit
  controllerComponentLabel: linkerd.io/control-plane-component
  controllerNamespaceLabel: linkerd.io/control-plane-ns
  linkerdNamespaceLabel: linkerd.io/is-control-plane


enableH2Upgrade: true

omitWebhookSideEffects: false
webhookFailurePolicy: Ignore

# controller configuration
controllerImage: gcr.io/linkerd-io/controller
controllerLogLevel: &controller_log_level info
controllerReplicas: 1
controllerUID: 2103

# web dashboard configuration
dashboard:
  replicas: 1

# debug configuration
debugContainer:
  image:
    name: gcr.io/linkerd-io/debug
    pullPolicy: *image_pull_policy
    version: *linkerd_version

# identity configuration
identity:
  issuer:
    scheme: linkerd.io/tls

    clockSkewAllowance: 20s

    # must match the expiry date in crtPEM
    crtExpiry:

    # control plane annotation - do not edit
    crtExpiryAnnotation: linkerd.io/identity-issuer-expiry

    issuanceLifetime: 86400s

    tls:
      # PEM-encoded certificate
      crtPEM: |

      # PEM-encoded ECDSA private key
      keyPEM: |

# grafana configuration
grafanaImage: gcr.io/linkerd-io/grafana
grafanaUserRole: Editor

# heartbeat configuration
disableHeartBeat: false
heartbeatSchedule: "0 0 * * *"

# prometheus configuration
prometheusImage: prom/prometheus:v2.15.2
prometheusLogLevel: *controller_log_level

# proxy injector configuration
proxyInjector:
  # if empty, Helm will auto-generate these fields
  crtPEM: |

  keyPEM: |

# service profile validator configuration
profileValidator:
  # if empty, Helm will auto-generate these fields
  crtPEM: |

  keyPEM: |

# tap configuration
tap:
  # if empty, Helm will auto-generate these fields
  crtPEM: |

  keyPEM: |

# web configuration
webImage: gcr.io/linkerd-io/web

# Node selection constraints for control-plane components
# https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector.
nodeSelector:
  beta.kubernetes.io/os: linux

kubectlImage:
  registry: quay.io
  name: giantswarm/docker-kubectl
  tag: 933ac043b7bec33104aac58b16849ea28bace26c
  pullPolicy: IfNotPresent
