version: 2.1
orbs:
  architect: giantswarm/architect@dev:ae81000a09fe66fba8235e5bccc584141f2f8ffa

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          name: "package and push linkerd-control-plane chart"
          context: architect
          executor: "app-build-suite"
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "linkerd-control-plane"
          persist_chart_archive: true
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/run-tests-with-ats:
          name: execute chart tests
          filters:
            # Do not trigger the job on merge to main.
            branches:
              ignore:
                - main
          requires:
            - "package and push linkerd-control-plane chart"
