version: 2.1
orbs:
  architect: giantswarm/architect@4.14.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          name: "package and push linkerd2 chart"
          context: architect
          executor: "app-build-suite"
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "linkerd2-app"
          persist_chart_archive: true
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/run-tests-with-ats:
          name: execute chart tests
          app-test-suite_container_tag: "0.2.3-beta.1-50d0b68c62f0324ef11c45f515bca87ad09217c2"
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
          requires:
            - "package and push linkerd2 chart"
