---
###
### linkerd-collector RBAC
###
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{.Values.collector.name}}
  namespace: {{.Release.namespace}}
  labels:
    {{.Values.global.controllerComponentLabel}}: {{.Values.collector.name}}
    {{.Values.global.controllerNamespaceLabel}}: {{.Release.namespace}}
---
###
### linkerd-jaeger RBAC
###
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{.Values.jaeger.name}}
  namespace: {{.Release.namespace}}
  labels:
    {{.Values.global.controllerComponentLabel}}: {{.Values.jaeger.name}}
    {{.Values.global.controllerNamespaceLabel}}: {{.Release.namespace}}
