{{- if .Values.global.grafana.enabled }}
---
###
### Grafana RBAC
###
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{.Values.name}}
  namespace: {{.Release.Namespace}}
  labels:
    {{.Values.global.controllerComponentLabel}}: grafana
    {{.Values.global.controllerNamespaceLabel}}: {{.Release.Namespace}}
{{- include "partials.image-pull-secrets" . }}
{{- end }}
