{{if .Values.identity -}}
{{if and (.Values.identity.issuer) (eq .Values.identity.issuer.scheme "linkerd.io/cert-manager") -}}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: global-config-creator
  namespace: {{ .Release.namespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
  labels:
    app: global-config-creator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - linkerd-config
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - linkerd-identity-issuer
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - linkerd-{{ .Release.namespace }}-control-plane
  verbs:
  - "use"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: global-config-creator
  namespace: {{ .Release.namespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
  labels:
    app: global-config-creator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: global-config-creator
  namespace: {{ .Release.namespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
  labels:
    app: global-config-creator
subjects:
  - kind: ServiceAccount
    name: global-config-creator
    namespace: {{ .Release.namespace }}
roleRef:
  kind: Role
  name: global-config-creator
  namespace: {{ .Release.namespace }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: global-config-creator
  namespace: {{ .Release.namespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
  labels:
    app: global-config-creator
spec:
  template:
    spec:
      serviceAccountName: global-config-creator
      containers:
      - name: global-config-creator
        image: "{{ .Values.kubectlImage.registry }}/{{ .Values.kubectlImage.name }}:{{ .Values.kubectlImage.tag }}"
        imagePullPolicy: "{{ .Values.kubectlImage.pullPolicy }}"
        command:
        - /bin/sh
        - -e
        - -x
        - -c
        - >-
          while true; do 
              export CERT=`kubectl -n {{ .Release.namespace }} get secret linkerd-identity-issuer -o jsonpath="{.data['ca\.crt']}" | base64 -d`;
              if [ $? -eq 0 ] && [ ! -z "$CERT" ]; then 
                  break; 
              fi; 
              echo \"waiting for cert\"; 
              sleep 1; 
          done; 
          while true; do 
              kubectl -n {{ .Release.namespace }} get cm linkerd-config -o yaml --export > /tmp/config.yaml; 
              if [ $? -neq 0 ]; then 
                  echo "waiting for config"; 
                  sleep 1;
                  continue; 
              fi; 
              grep "\"proxyVersion\": \"{{ splitList "." .Values.global.proxy.image.version | join "\\." }}\",$" /tmp/config.yaml >/dev/null
              if [ $? -neq 0 ]; then 
                  echo "waiting for updated config"; 
                  sleep 1;
                  continue; 
              fi; 
              break;
          done; 
          awk -v CERT="$CERT" 'BEGIN{gsub("\n", "\\n", CERT)}; {gsub("REPLACE_ME", CERT);print $0}' /tmp/config.yaml > /tmp/config-out.yaml;
          kubectl -n {{ .Release.namespace }} replace configmap linkerd-config -f /tmp/config-out.yaml;
      restartPolicy: Never
  backoffLimit: 6
{{- end}}
{{- end}}
