{{ if not .Values.disableHeartBeat -}}
---
###
### Heartbeat RBAC
###
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: linkerd-heartbeat
  namespace: {{.Release.namespace}}
  labels:
    {{.Values.global.controllerNamespaceLabel}}: {{.Release.namespace}}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
  resourceNames: ["linkerd-config"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: linkerd-heartbeat
  namespace: {{.Release.namespace}}
  labels:
    {{.Values.global.controllerNamespaceLabel}}: {{.Release.namespace}}
roleRef:
  kind: Role
  name: linkerd-heartbeat
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: linkerd-heartbeat
  namespace: {{.Release.namespace}}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: linkerd-heartbeat
  namespace: {{.Release.namespace}}
  labels:
    {{.Values.global.controllerComponentLabel}}: heartbeat
    {{.Values.global.controllerNamespaceLabel}}: {{.Release.namespace}}
{{- end }}
