---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: namespace-tagger
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
  labels:
    app: namespace-tagger
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  resourceNames:
  - {{ .Values.global.namespace }}
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - linkerd-config
  verbs:
  - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespace-tagger
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
  labels:
    app: namespace-tagger
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: namespace-tagger
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-14"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
  labels:
    app: namespace-tagger
subjects:
  - kind: ServiceAccount
    name: namespace-tagger
    namespace: {{ .Values.global.namespace }}
roleRef:
  kind: Role
  name: namespace-tagger
  namespace: {{ .Values.global.namespace }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: namespace-tagger
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
  labels:
    app: namespace-tagger
spec:
  template:
    spec:
      serviceAccountName: namespace-tagger
      containers:
      - name: namespace-tagger
        image: "{{ .Values.kubectlImage.registry }}/{{ .Values.kubectlImage.name }}:{{ .Values.kubectlImage.tag }}"
        imagePullPolicy: "{{ .Values.kubectlImage.pullPolicy }}"
        command:
        - /bin/sh
        - -e
        - -x
        - -c
        - >-
          kubectl annotate --overwrite ns {{ .Values.global.namespace }} {{.Values.global.proxyInjectAnnotation}}={{.Values.global.proxyInjectDisabled}};
          kubectl label --overwrite ns {{ .Values.global.namespace }} {{.Values.global.linkerdNamespaceLabel}}="true";
          kubectl label --overwrite ns {{ .Values.global.namespace }} config.linkerd.io/admission-webhooks=disabled;
          kubectl -n {{ .Values.global.namespace }} delete configmap linkerd-config || true;
      restartPolicy: Never
  backoffLimit: 6
