{{with .Values -}}
{{if .Identity -}}
{{if and (.Identity.Issuer) (eq .Identity.Issuer.Scheme "linkerd.io/cert-manager") -}}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: linkerd-selfsigning-issuer
  namespace: {{.Namespace}}
  labels:
    {{.ControllerComponentLabel}}: identity
    {{.ControllerNamespaceLabel}}: {{.Namespace}}
  annotations:
    {{.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .LinkerdVersion) .CliVersion}}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
spec:
  selfSigned: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: {{.Namespace}}
  labels:
    {{.ControllerComponentLabel}}: identity
    {{.ControllerNamespaceLabel}}: {{.Namespace}}
  annotations:
    {{.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .LinkerdVersion) .CliVersion}}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
spec:
  secretName: linkerd-identity-issuer
  commonName: identity.linkerd.{{.ClusterDomain}}
  isCA: true
  keyAlgorithm: ecdsa
  issuerRef:
    name: linkerd-selfsigning-issuer
{{- end}}
{{- end}}
{{- end}}
