{{if .Values.identity -}}
{{if and (.Values.identity.issuer) (eq .Values.identity.issuer.scheme "linkerd.io/cert-manager") -}}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: linkerd-selfsigning-issuer
  namespace: {{.Values.global.namespace}}
  labels:
    {{.Values.global.controllerComponentLabel}}: identity
    {{.Values.global.controllerNamespaceLabel}}: {{.Values.global.namespace}}
  annotations:
    {{.Values.global.createdByAnnotation}}: {{ printf "linkerd/helm %s" .Values.global.linkerdVersion }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
spec:
  selfSigned: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: {{.Values.global.namespace}}
  labels:
    {{.Values.global.controllerComponentLabel}}: identity
    {{.Values.global.controllerNamespaceLabel}}: {{.Values.global.namespace}}
  annotations:
    {{.Values.global.createdByAnnotation}}: {{ printf "linkerd/helm %s" .Values.global.linkerdVersion }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
spec:
  secretName: linkerd-identity-issuer
  commonName: identity.{{.Values.global.namespace}}.{{.Values.global.clusterDomain}}
  isCA: true
  keyAlgorithm: ecdsa
  issuerRef:
    name: linkerd-selfsigning-issuer
{{- end}}
{{- end}}
