---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: linkerd-janitor
  namespace: {{ .Values.Namespace }}
  annotations:
    "helm.sh/hook": "post-delete"
    #    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
  labels:
    app: linkerd-janitor
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceName:
  - linkerd-config
  verbs:
  - "delete"
- apiGroups:
  - ""
  resources:
  - secrets
  resourceName:
  - linkerd-identity-issuer
  - linkerd-ca-tls
  verbs:
  - "delete"
- apiGroups:
  - "certmanager.k8s.io"
  resources:
  - "issuer"
  resourceName:
  - linkerd-ca-issuer
  - linkerd-selfsigning-issuer
  verbs:
  - delete
- apiGroups:
  - "certmanager.k8s.io"
  resources:
  - "certificate"
  resourceName:
  - linkerd-ca
  - linkerd
  verbs:
  - delete
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - linkerd-{{.Values.Namespace}}-control-plane
  verbs:
  - "use"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: linkerd-janitor
  namespace: {{ .Values.Namespace }}
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
  namespace: {{ .Values.Namespace }}
  labels:
    app: linkerd-janitor
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: linkerd-janitor
  namespace: {{ .Values.Namespace }}
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
  labels:
    app: linkerd-janitor
subjects:
  - kind: ServiceAccount
    name: linkerd-janitor
    namespace: {{ .Values.Namespace }}
roleRef:
  kind: Role
  name: linkerd-janitor
  namespace: {{ .Values.Namespace }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: linkerd-janitor
  namespace: {{ .Values.Namespace }}
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
  labels:
    app: linkerd-janitor
spec:
  template:
    spec:
      serviceAccountName: linkerd-janitor
      containers:
      - name: janitor
        image: "bitnami/kubectl:latest"
        command:
        - /bin/bash
        - -e
        - -c
        - |
          kubectl -n linkerd delete secret linkerd-ca-tls;
          kubectl -n linkerd delete secret linkerd-identity-issuer;
      restartPolicy: Never
  backoffLimit: 6
