---
kind: ConfigMap
apiVersion: v1
metadata:
  name: linkerd-config
  namespace: {{.Release.namespace}}
  labels:
    {{.Values.global.controllerComponentLabel}}: controller
    {{.Values.global.controllerNamespaceLabel}}: {{.Release.namespace}}
  annotations:
    {{.Values.global.createdByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.global.linkerdVersion) .Values.global.cliVersion}}
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-4"
data:
  global: |
  {{- if .Values.configs -}}
  {{- if .Values.configs.global -}}
  {{.Values.configs.global | nindent 4}}
  {{- end }}
  {{- else -}}
  {{- include "linkerd.configs.global" . | nindent 4}}
  {{- end }}
  proxy: |
  {{- if .Values.configs -}}
  {{- if .Values.configs.proxy -}}
  {{.Values.configs.proxy | nindent 4}}
  {{- end }}
  {{- else -}}
  {{- include "linkerd.configs.proxy" . | nindent 4}}
  {{- end }}
  install: |
  {{- if .Values.configs -}}
  {{- if .Values.configs.install -}}
  {{.Values.configs.install | nindent 4}}
  {{- end }}
  {{- else -}}
  {{- include "linkerd.configs.install" . | nindent 4}}
  {{- end }}
