{{if .Values.identity -}}
---
###
### Identity Controller Service RBAC
###
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-{{.Release.namespace}}-identity
  labels:
    {{.Values.global.controllerComponentLabel}}: identity
    {{.Values.global.controllerNamespaceLabel}}: {{.Release.namespace}}
rules:
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-{{.Release.namespace}}-identity
  labels:
    {{.Values.global.controllerComponentLabel}}: identity
    {{.Values.global.controllerNamespaceLabel}}: {{.Release.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: linkerd-{{.Release.namespace}}-identity
subjects:
- kind: ServiceAccount
  name: linkerd-identity
  namespace: {{.Release.namespace}}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: linkerd-identity
  namespace: {{.Release.namespace}}
  labels:
    {{.Values.global.controllerComponentLabel}}: identity
    {{.Values.global.controllerNamespaceLabel}}: {{.Release.namespace}}
{{ end -}}
