{{with .Values -}}
{{if .Identity -}}
{{if and (.Identity.Issuer) (eq .Identity.Issuer.Scheme "linkerd.io/cert-manager") -}}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: linkerd-selfsigning-issuer
  namespace: {{.Namespace}}
  labels:
    {{.ControllerComponentLabel}}: identity
    {{.ControllerNamespaceLabel}}: {{.Namespace}}
  annotations:
    {{.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .LinkerdVersion) .CliVersion}}
spec:
  selfSigned: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: linkerd-ca
  namespace: {{.Namespace}}
  labels:
    {{.ControllerComponentLabel}}: identity
    {{.ControllerNamespaceLabel}}: {{.Namespace}}
  annotations:
    {{.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .LinkerdVersion) .CliVersion}}
spec:
  secretName: linkerd-ca-tls
  commonName: linkerd
  isCA: true
  issuerRef:
    name: linkerd-selfsigning-issuer
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: linkerd-ca-issuer
  namespace: {{.Namespace}}
  labels:
    {{.ControllerComponentLabel}}: identity
    {{.ControllerNamespaceLabel}}: {{.Namespace}}
  annotations:
    {{.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .LinkerdVersion) .CliVersion}}
spec:
  ca:
    secretName: linkerd-ca-tls
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: linkerd
  namespace: {{.Namespace}}
  labels:
    {{.ControllerComponentLabel}}: identity
    {{.ControllerNamespaceLabel}}: {{.Namespace}}
  annotations:
    {{.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .LinkerdVersion) .CliVersion}}
spec:
  secretName: linkerd-identity-issuer
  commonName: linkerd
  issuerRef:
    name: linkerd-ca-issuer
  dnsNames:
  - identity.linkerd.{{.ClusterDomain}}
{{- end}}
{{- end}}
{{- end}}
