{{- /*
  This config-map is used to store the configuration of add-ons, which is useful during upgrades.
  This is required, as some add-ons can be enabled by default.
  Whenever an add-on is disabled, we just store the enabled flag for it and remove any extra configuration
  passed for the add-on.
*/ -}}
---
###
### linkerd add-ons configuration
###
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: linkerd-config-addons
  namespace: {{.Values.global.namespace}}
  labels:
    {{.Values.global.controllerNamespaceLabel}}: {{.Values.global.namespace}}
  annotations:
    {{.Values.global.createdByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.global.linkerdVersion) .Values.global.cliVersion}}
data:
  values: |-
    global:
      grafanaUrl: "{{.Values.global.grafanaUrl}}"
    grafana:
      {{- include "linkerd.addons.sanitize-config" .Values.grafana}}
    tracing:
      {{- include "linkerd.addons.sanitize-config" .Values.tracing}}
